version: '3.7'

services: 
  hlservice.identity:
    environment:
      LogConfigPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shares/Configs:/app/configs
  hlservice.gateway:
    volumes:
      - ../../src/Shares/Configs:/app/configs