version: '3.7'

services:
  hlservice.customer:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.customer"
      SwaggerDes: "客户信息管理服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18080:8080"

  hlservice.identity:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      ConnectionString: "Server=mysql;Database=surging_demo_identity;Uid=root;Port=3306;Pwd=Surging!P4ss"
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.identity"
      SwaggerDes: "微服务集群身份认证与授权组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18081:8080"

  hlservice.order:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.order"
      SwaggerDes: "订单微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18082:8080"

  hlservice.product:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.product"
      SwaggerDes: "产品管理微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18083:8080"

  hlservice.schedule:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${SCHEDULE_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.schedule"
      SwaggerDes: "任务调度微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18084:8080"

  hlservice.stock:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.stock"
      SwaggerDes: "库存管理微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18085:8080"

  hlservice.organization:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.organization"
      SwaggerDes: "组织机构微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18086:8080"

  hlservice.basicdata:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      SwaggerTitle: "hlservice.basicdata"
      SwaggerDes: "基础数据微服务组件API文档"
      SupportName: "LiuHongliang"
      SupportEmail: 1029765111@qq.com
    ports:
      - "18087:8080"
  hlservice.wsserver:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${WS_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
    ports:
      - "196:96"